### ISSUE TITLE
Python Bindings Viewer

### ISSUE THREAD

**Issue by cubic23** [libigl/libigl#228]
When I compile the libigl Python bindings on Ubuntu 15.10 (with g++ 4.8), the compilation works but OpenGL is not found and therefore the viewer is not built. Changing line 22 of CMakeLists from `find_package(OPENGL QUIET)` to `find_package(OpenGL QUIET)` fixes this, but then nanogui is linked as a static library and cannot be linked by the shared library igl.so. The linker message is: 

> /usr/bin/ld: nanogui/libnanogui.a(context.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC

Is there way to make it build on Linux including OpenGL and (one of) the viewer(s)?

Thanks!

**Comment by danielepanozzo** [comment]
Fixed in f528c4d. Could you please confirm (and close the issue) if it works for you on Ubuntu 15.10? (We are currently testing the linux build on 12.04).

**Comment by cubic23** [comment]
Hi Daniele,
thanks, but this did not completely fix the problem. I created the pull request #230 with changes that resolve the problem of missing symbols on Ubuntu 15.10. Is there a specific reason for the manual addition of the dependent libraries?

The Python bindings work now, however, there is no GUI available in the viewer (I added `LIBIGL_VIEWER_WITH_NANOGUI` to cmake but this doesn't solve the problem). Do you have an idea how to fix this?

**Comment by danielepanozzo** [comment]
Thank you for the pull request, I merged it. The manual addition of the dependent libraries was there to go around a bug in the cmake findopengl file bundled with some older ubuntus. This does not seem to be a problem anymore and your solution is great.

No idea how to solve the second problem, I will take a look.

**Comment by danielepanozzo** [comment]
Fixed in f63ff33c91a8453b85b2782a2f5065d3b20f49ba
Please close the issue if it fixes it for you.

**Comment by cubic23** [comment]
Thanks, the GUI works now with this definition.
