### ISSUE TITLE
vs2013 viewer.launch() abort issue

### ISSUE THREAD

**Issue by thebirdyan** [libigl/libigl#98]
I'm trying out the tutorial code with vs 2013, it always gives the R6010 - abort() has been called error. If I step into it, it will give a eigen related error: assertion failed: (reinterpret_cast<size_t>(array) & 0xf) == 0 && "this assertion is explained here: 
However I can't really locate where it really comes from as it doesn't show at the same place, but always in the viewer functions...

Any idea how to solve this? Thanks!

**Comment by alecjacobson** [comment]
for which tutorial program is this happening?

**Comment by danielepanozzo** [comment]
I can reproduce it with VS2015, I just committed a fix. Could you please confirm if it also solves your problem on VS2013?

**Comment by thebirdyan** [comment]
I test 102_DrawMesh, and some other tutorials that draw the scene, it all have this problem. I'm using 32bit, Eigen322. I tried again with your updated code(viewerCore.cpp, right?), the problem remains...

**Comment by danielepanozzo** [comment]
Could you please compile in debug mode and paste here the stack trace? I cannot reproduce it on VS2015 64bit. Does it happen both in debug and release mode?

Another thing to try: try to add add_definitions(-DEIGEN_DONT_ALIGN) to the cmake file.
